const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: "CHANGE_LANGUAGE",

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //Movies
    FETCH_MOVIE_SUCCESS: 'FETCH_MOVIE_SUCCESS',
    FETCH_MOVIE_FAIL: 'FETCH_MOVIE_FAIL',

    FETCH_MOVIE_TOP_RATED_SUCCESS: 'FETCH_MOVIE_TOP_RATED_SUCCESS',
    FETCH_MOVIE_TOP_RATED_FAIL: 'FETCH_MOVIE_TOP_RATED_FAIL',

    FETCH_DETAIL_MOVIE_SUCCESS: 'FETCH_DETAIL_MOVIE_SUCCESS',
    FETCH_DETAIL_MOVIE_FAIL: 'FETCH_DETAIL_MOVIE_FAIL',

    FETCH_VIDEO_MOVIE_SUCCESS: 'FETCH_VIDEO_MOVIE_SUCCESS',
    FETCH_VIDEO_MOVIE_FAIL: 'FETCH_VIDEO_MOVIE_FAIL',

    FETCH_GENRES_MOVIE_SUCCESS: 'FETCH_GENRES_MOVIE_SUCCESS',
    FETCH_GENRES_MOVIE_FAIL: 'FETCH_GENRES_MOVIE_FAIL',

    FETCH_CREDIT_MOVIE_SUCCESS: 'FETCH_CREDIT_MOVIE_SUCCESS',
    FETCH_CREDIT_MOVIE_FAIL: 'FETCH_CREDIT_MOVIE_FAIL'

})

export default actionTypes;